POST http://localhost:3001/api/anime
content-type: application/json
Authorization: bearer token

{
    "name": "Anime Name",
    "link": "https://www.wcofun.com/anime/{anime_name}",
    "watched": false
}